# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='Visit Date')),
                ('patient_type', models.CharField(max_length=1, verbose_name='Patient Type')),
                ('wait_time', models.IntegerField(default=0, verbose_name='Wait Time')),
            ],
        ),
    ]
